### ISSUE TITLE
「启动失败」app:transformClassesWithDesugarForDebug

### ISSUE THREAD

**Issue by hornhuang** [HackSoul/zhihu-flutter#13]
解决了：Execution failed for task ':app:processDebugResources'.问题 [启动失败](https://github.com/xujiyou/zhihu-flutter/issues/11) 后遇到的新问题

主要：
faild：app:transformClassesWithDesugarForDebug

更多：
Running Gradle task 'assembleDebug'...
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
Exception in thread "main" java.lang.TypeNotPresentException: Type com.google.android.play.core.tasks.OnSuccessListener not present
	at sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:85)
	at sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:63)
	at sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:41)
	at java.lang.invoke.MethodType.fromMethodDescriptorString(MethodType.java:1067)
	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:399)
	at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(Unknown Source)
	at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)
Caused by: java.lang.ClassNotFoundException: Class com.google.android.play.core.tasks.OnSuccessListener not found
	at com.google.devtools.build.android.desugar.HeaderClassLoader.findClass(HeaderClassLoader.java:53)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:83)
	... 14 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDesugarForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {--input

**Comment by hornhuang** [comment]
i think, the reason maybe flutter sdk version is wrong,.
but i don't know the sdk verison for this project, hope author provide it.
best wishes~ ❤️
